// flow-typed signature: 949335ac41e264a8c3b980041cff896c
// flow-typed version: <<STUB>>/atomicjs_v^3.2.1/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'atomicjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'atomicjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'atomicjs/dist/atomic' {
  declare module.exports: any;
}

declare module 'atomicjs/dist/atomic.min' {
  declare module.exports: any;
}

declare module 'atomicjs/docs/dist/atomic' {
  declare module.exports: any;
}

declare module 'atomicjs/docs/dist/atomic.min' {
  declare module.exports: any;
}

declare module 'atomicjs/gulpfile' {
  declare module.exports: any;
}

declare module 'atomicjs/src/js/atomic' {
  declare module.exports: any;
}

declare module 'atomicjs/test/karma.conf' {
  declare module.exports: any;
}

declare module 'atomicjs/test/spec/atomic-spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'atomicjs/dist/atomic.js' {
  declare module.exports: $Exports<'atomicjs/dist/atomic'>;
}
declare module 'atomicjs/dist/atomic.min.js' {
  declare module.exports: $Exports<'atomicjs/dist/atomic.min'>;
}
declare module 'atomicjs/docs/dist/atomic.js' {
  declare module.exports: $Exports<'atomicjs/docs/dist/atomic'>;
}
declare module 'atomicjs/docs/dist/atomic.min.js' {
  declare module.exports: $Exports<'atomicjs/docs/dist/atomic.min'>;
}
declare module 'atomicjs/gulpfile.js' {
  declare module.exports: $Exports<'atomicjs/gulpfile'>;
}
declare module 'atomicjs/src/js/atomic.js' {
  declare module.exports: $Exports<'atomicjs/src/js/atomic'>;
}
declare module 'atomicjs/test/karma.conf.js' {
  declare module.exports: $Exports<'atomicjs/test/karma.conf'>;
}
declare module 'atomicjs/test/spec/atomic-spec.js' {
  declare module.exports: $Exports<'atomicjs/test/spec/atomic-spec'>;
}
