// flow-typed signature: 17dc6cad142379cd8edeaf293b92f592
// flow-typed version: <<STUB>>/compass-mixins_v^0.12.10/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'compass-mixins'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'compass-mixins' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'compass-mixins/test/compileSpec' {
  declare module.exports: any;
}

declare module 'compass-mixins/test/css3/borderRadiusSpec' {
  declare module.exports: any;
}

declare module 'compass-mixins/test/css3/boxShadowSpec' {
  declare module.exports: any;
}

declare module 'compass-mixins/test/css3/boxSizingSpec' {
  declare module.exports: any;
}

declare module 'compass-mixins/test/css3/flexboxSpec' {
  declare module.exports: any;
}

declare module 'compass-mixins/test/css3/imagesSpec' {
  declare module.exports: any;
}

declare module 'compass-mixins/test/css3/transitionSpec' {
  declare module.exports: any;
}

declare module 'compass-mixins/test/functionsSpec' {
  declare module.exports: any;
}

declare module 'compass-mixins/test/helper/compare' {
  declare module.exports: any;
}

declare module 'compass-mixins/test/helper/property' {
  declare module.exports: any;
}

declare module 'compass-mixins/test/helper/render' {
  declare module.exports: any;
}

declare module 'compass-mixins/test/helper/ruleset' {
  declare module.exports: any;
}

// Filename aliases
declare module 'compass-mixins/test/compileSpec.js' {
  declare module.exports: $Exports<'compass-mixins/test/compileSpec'>;
}
declare module 'compass-mixins/test/css3/borderRadiusSpec.js' {
  declare module.exports: $Exports<'compass-mixins/test/css3/borderRadiusSpec'>;
}
declare module 'compass-mixins/test/css3/boxShadowSpec.js' {
  declare module.exports: $Exports<'compass-mixins/test/css3/boxShadowSpec'>;
}
declare module 'compass-mixins/test/css3/boxSizingSpec.js' {
  declare module.exports: $Exports<'compass-mixins/test/css3/boxSizingSpec'>;
}
declare module 'compass-mixins/test/css3/flexboxSpec.js' {
  declare module.exports: $Exports<'compass-mixins/test/css3/flexboxSpec'>;
}
declare module 'compass-mixins/test/css3/imagesSpec.js' {
  declare module.exports: $Exports<'compass-mixins/test/css3/imagesSpec'>;
}
declare module 'compass-mixins/test/css3/transitionSpec.js' {
  declare module.exports: $Exports<'compass-mixins/test/css3/transitionSpec'>;
}
declare module 'compass-mixins/test/functionsSpec.js' {
  declare module.exports: $Exports<'compass-mixins/test/functionsSpec'>;
}
declare module 'compass-mixins/test/helper/compare.js' {
  declare module.exports: $Exports<'compass-mixins/test/helper/compare'>;
}
declare module 'compass-mixins/test/helper/property.js' {
  declare module.exports: $Exports<'compass-mixins/test/helper/property'>;
}
declare module 'compass-mixins/test/helper/render.js' {
  declare module.exports: $Exports<'compass-mixins/test/helper/render'>;
}
declare module 'compass-mixins/test/helper/ruleset.js' {
  declare module.exports: $Exports<'compass-mixins/test/helper/ruleset'>;
}
