// flow-typed signature: de3a373304e30c795cff441d54c74fde
// flow-typed version: <<STUB>>/cssobj_v^1.2.3/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cssobj'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cssobj' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cssobj/dist/cssobj.amd' {
  declare module.exports: any;
}

declare module 'cssobj/dist/cssobj.cjs' {
  declare module.exports: any;
}

declare module 'cssobj/dist/cssobj.es' {
  declare module.exports: any;
}

declare module 'cssobj/dist/cssobj.iife' {
  declare module.exports: any;
}

declare module 'cssobj/dist/cssobj.min' {
  declare module.exports: any;
}

declare module 'cssobj/dist/cssobj.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cssobj/dist/cssobj.amd.js' {
  declare module.exports: $Exports<'cssobj/dist/cssobj.amd'>;
}
declare module 'cssobj/dist/cssobj.cjs.js' {
  declare module.exports: $Exports<'cssobj/dist/cssobj.cjs'>;
}
declare module 'cssobj/dist/cssobj.es.js' {
  declare module.exports: $Exports<'cssobj/dist/cssobj.es'>;
}
declare module 'cssobj/dist/cssobj.iife.js' {
  declare module.exports: $Exports<'cssobj/dist/cssobj.iife'>;
}
declare module 'cssobj/dist/cssobj.min.js' {
  declare module.exports: $Exports<'cssobj/dist/cssobj.min'>;
}
declare module 'cssobj/dist/cssobj.umd.js' {
  declare module.exports: $Exports<'cssobj/dist/cssobj.umd'>;
}
