// flow-typed signature: dd4f57f2c90c28ba9a69a1ac20d7bfe4
// flow-typed version: <<STUB>>/style-inject_v0.3.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'style-inject'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'style-inject' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'style-inject/dist/style-inject.es' {
  declare module.exports: any;
}

declare module 'style-inject/dist/style-inject' {
  declare module.exports: any;
}

// Filename aliases
declare module 'style-inject/dist/style-inject.es.js' {
  declare module.exports: $Exports<'style-inject/dist/style-inject.es'>;
}
declare module 'style-inject/dist/style-inject.js' {
  declare module.exports: $Exports<'style-inject/dist/style-inject'>;
}
