// flow-typed signature: bdf9040e0bd849e09673abae4297d03b
// flow-typed version: <<STUB>>/rollup-starter-lib_v1.0.0/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-starter-lib'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-starter-lib' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rollup-starter-lib/dist/section.cjs' {
  declare module.exports: any;
}

declare module 'rollup-starter-lib/dist/section.esm' {
  declare module.exports: any;
}

declare module 'rollup-starter-lib/dist/section.umd' {
  declare module.exports: any;
}

declare module 'rollup-starter-lib/rollup.config' {
  declare module.exports: any;
}

declare module 'rollup-starter-lib/src/index' {
  declare module.exports: any;
}

declare module 'rollup-starter-lib/src/sectionA/index' {
  declare module.exports: any;
}

declare module 'rollup-starter-lib/src/sectionB/index' {
  declare module.exports: any;
}

declare module 'rollup-starter-lib/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rollup-starter-lib/dist/section.cjs.js' {
  declare module.exports: $Exports<'rollup-starter-lib/dist/section.cjs'>;
}
declare module 'rollup-starter-lib/dist/section.esm.js' {
  declare module.exports: $Exports<'rollup-starter-lib/dist/section.esm'>;
}
declare module 'rollup-starter-lib/dist/section.umd.js' {
  declare module.exports: $Exports<'rollup-starter-lib/dist/section.umd'>;
}
declare module 'rollup-starter-lib/rollup.config.js' {
  declare module.exports: $Exports<'rollup-starter-lib/rollup.config'>;
}
declare module 'rollup-starter-lib/src/index.js' {
  declare module.exports: $Exports<'rollup-starter-lib/src/index'>;
}
declare module 'rollup-starter-lib/src/sectionA/index.js' {
  declare module.exports: $Exports<'rollup-starter-lib/src/sectionA/index'>;
}
declare module 'rollup-starter-lib/src/sectionB/index.js' {
  declare module.exports: $Exports<'rollup-starter-lib/src/sectionB/index'>;
}
declare module 'rollup-starter-lib/test/test.js' {
  declare module.exports: $Exports<'rollup-starter-lib/test/test'>;
}
